import pandas as pd

# 定义前缀和后缀数据
prefixes = {
    "ore":"~原矿",
    "rawOre":"~粗矿",
    "crushed":"粉碎~",
    "crushedPurified":"洗净~",
    "crushedCentrifuged":"离心~",
    "dust":"~粉",
    "dustPure":"洁净~粉",
    "dustlmpure":"含杂~粉",
    "nugget":"~粒"
}

suffixes_special = [
    ("Amber","琥珀","洗-筛"),
    ("Apatite","磷灰石","洗-热-粉"),
    ("BArTiMaEuSNek","BArTiMaEuSNek","洗-筛"),
    ("Bauxite","铝土矿","洗-热-粉"),
    ("Coal","煤","洗-筛"),
    ("Cooperite","硫铂矿","洗or浸洗(Hg)"),
    ("Diamond","钻石","洗-筛"),
    ("Dilithium","双锂","洗-筛"),
    ("Emerald","绿宝石","洗-筛"),
    ("GreenSapphire","绿色蓝宝石","洗-筛"),
    ("Galena","方铅矿","洗-保留"),
    ("Ilmenite","钛铁矿","浸洗（硫酸）"),
    ("InfusedAir","风之蕴魔石","洗-筛"),
    ("InfusedEarth","地之蕴魔石","洗-筛"),
    ("InfusedEntropy","混沌蕴魔石","洗-筛"),
    ("InfusedFire","火之蕴魔石","洗-筛"),
    ("InfusedWater","水之蕴魔石","洗-筛"),
    ("InfusedOrder","秩序蕴魔石","洗-筛"),
    ("Iridium","铱","浸洗(Hg)-热-粉"),
    ("Lapis","青金石","洗-筛"),
    ("Lead","铅","工业高炉"),
    ("Lepidolite","锂云母","洗-浸洗(盐酸)"),
    ("Meteoriclron","陨铁","浸洗(Hg)-热-粉"),
    ("Mithril","秘银","浸洗(Hg)-粉-离"),
    ("Mytryl","深空秘银","粉-离"),
    ("NetherQuartz","下界石英","洗-筛"),
    ("NetherStar","下界之星","洗-筛"),
    ("Nickel","镍","浸洗(Hg)-粉-离"),
    ("Olivine","橄榄石","洗-筛"),
    ("Orundum","合成玉","洗-筛"),
    ("Osmium","锇","浸洗(Hg)-热-粉"),
    ("Platinum","铂","浸洗(Hg)-热-粉"),
    ("PlatinumMetallicPowder","铂金属","浸洗(Hg)-热-粉"),
    ("Prasiolite","堇云石","洗-筛"),
    ("Pyrochlore","烧绿石","洗-热-粉"),
    ("Pyrolusite","软锰矿","洗-热-粉"),
    ("Quartzite","石英岩","洗-筛"),
    ("RedZircon","红锆石","洗-筛"),
    ("Roquesite","硫铟铜","保留"),
    ("Rubracium","褐铜","粉-粉"),
    ("Ruby","红宝石","洗-筛"),
    ("Salt","盐","洗-筛"),
    ("Sapphire","蓝宝石","洗-筛"),
    ("Scheelite","白钨矿","洗-保留"),
    ("Molybdenite","辉钼矿","洗-保留"),
    ("Molybdenum","钼","洗-保留"),
    ("Sphalerite","闪锌矿","洗-保留"),
    ("Tanzanite","坦桑石","洗-筛"),
    ("Tiberium","泰伯利亚","洗-筛"),
]

suffixes_non_special = [
    ("Adamantium","精金"),
    ("AgarditeCd","菱铁矿（Cd）"),
    ("AgarditeLa","菱铁矿（La）"),
    ("AgarditeNd","菱铁矿（Nd）"),
    ("AgarditeY","菱铁矿（Y）"),
    ("Alduorite","神秘蓝金"),
    ("Almandine","铁铝榴石"),
    ("Aluminium","铝"),
    ("Aluminiumfluoride","氟化铝"),
    ("Alunite","明矾石"),
    ("Americium","镅"),
    ("Amethyst","紫水晶"),
    ("Andradite","钙铁榴石"),
    ("Antimony","锑"),
    ("Anycopper","铜"),
    ("Anyiron","铁"),
    ("Ardite","阿迪特"),
    ("Arsenic","砷"),
    ("Arsenopyrite","砷铁矿"),
    ("Asbestos","石棉"),
    ("Atheneite","砷汞钯"),
    ("BandedIron","带状铁矿"),
    ("Barite","重晶石"),
    ("Barium","钡"),
    ("Bastnasite","氟碳镧铈"),
    ("Bedrockium","基岩"),
    ("Beryllium","铍"),
    ("Bismuth","铋"),
    ("Bismuthinite","辉铋"),
    ("Bismutite","泡铋"),
    ("BlackPlutonium","黑钚"),
    ("BlueTopaz","蓝黄玉"),
    ("Borax","硼砂"),
    ("Bornite","斑铜"),
    ("BrownLimonite","棕褐铁矿"),
    ("Cadmium","镉"),
    ("Caesium","铯"),
    ("Calcite","方解石"),
    ("CalciumDisilicide","二硅化钙"),
    ("CalciumHydride","氢化钙"),
    ("Callistolce","木卫四冰"),
    ("Cassiterite","锡石"),
    ("Cerite","铈硅石"),
    ("Cerium","铈"),
    ("CertusQuartz","赛特斯石英"),
    ("Cheese","奶酪"),
    ("Chrome","铬"),
    ("Chromite","铬铁矿"),
    ("Chromo-Alumino-Povondraite","铬铝电气石"),
    ("Chrysotile","白石棉"),
    ("Cinnabar","朱砂"),
    ("Cobalt","钴"),
    ("Cobaltite","辉钴矿"),
    ("CosmicNeutronium","宇宙中子态素"),
    ("Crocoite","赤铅矿"),
    ("CrudeRhodiumMetal","粗制铑金属"),
    ("Cryolite","冰晶石"),
    ("CryoliteF","冰晶石F"),
    ("Darklron","玄铁"),
    ("Deeplron","深渊铁"),
    ("Desh","戴斯"),
    ("Diatomite","硅藻土"),
    ("Djurleite","久辉铜"),
    ("Dolomite","白云石"),
    ("Draconium","龙"),
    ("DraconiumAwakened","觉醒龙"),
    ("Duralumin","硬铝"),
    ("Dysprosium","镝"),
    ("Electrotine","蓝石"),
    ("Electrum","琥珀金"),
    ("ElectrumFlux","通流琥珀金"),
    ("Emery","金刚砂"),
    ("Enriched-NaquadahOxideMixture","氧化富集硅岩混合物"),
    ("Erbium","铒"),
    ("Europium","铕"),
    ("Fayalite","铁橄榄石"),
    ("Ferberite","钨铁"),
    ("Firestone","火石"),
    ("Florencite","磷铝铈矿"),
    ("Fluor-Buergerite","氟铁电气石"),
    ("Fluorcaphite","氟碳铈矿"),
    ("FluoriteF","氟石(F)"),
    ("Fluorspar","氟石"),
    ("FoolsRuby","尖晶石"),
    ("Force","力量"),
    ("Forcicium","力之宝石"),
    ("Forcillium","力场宝石"),
    ("Forsterite","镁橄榄石"),
    ("GadoliniteCe","硅铍钇矿(Ce)"),
    ("GadoliniteY","硅铍钇矿(Y)"),
    ("Gadolinium","钆"),
    ("GarnetRed","红石榴石"),
    ("GarnetYellow","黄石榴石"),
    ("Garnierite","硅镁镍矿"),
    ("Geikielite","镁钛矿"),
    ("Glauconite","海绿石"),
    ("Gold","金"),
    ("Graphite","石墨"),
    ("GreenFuchsite","绿铬云母"),
    ("Greenockite","硫镉"),
    ("Grossular","钙铝榴石"),
    ("Gypsum","石膏"),
    ("Hedenbergite","钙铁辉石"),
    ("HeeEndium","终末"),
    ("Hibonite","黑铝钙石"),
    ("Holmium","钬"),
    ("Huebnerite","钨酸锰"),
    ("Ichorium","灵宝"),
    ("Indium","铟"),
    ("InfinityCatalyst","无尽催化剂"),
    ("InfusedGold","注魔金"),
    ("IridiumMetalResidue","铱金属渣粉"),
    ("Iron","铁"),
    ("Jade","玉"),
    ("Jasper","碧玉"),
    ("Kyanite","蓝晶石"),
    ("LanthaniteCe","镧石(Ce)"),
    ("LanthaniteLa","镧石(La)"),
    ("LanthaniteNd","镧石()"),
    ("Lanthanum","镧"),
    ("Lazurite","蓝金石"),
    ("LeachResidue","浸出渣"),
    ("Ledox","深铅"),
    ("Lepersonnite","绿泥石"),
    ("Lignite","褐煤"),
    ("Lithium","锂"),
    ("Loellingite","斜方砷铁"),
    ("Lutetium","镥"),
    ("Magnesite","菱镁矿"),
    ("Magnesium","镁"),
    ("Magnetite","磁铁矿"),
    ("Malachite","孔雀石"),
    ("Manganese","锰"),
    ("Manyullyn","玛玉灵"),
    ("Mica","云母"),
    ("Mirabilite","芒硝"),
    ("MysteriousCrystal","神秘水晶"),
    ("Monazite","独居石"),
    ("Naquadah","硅岩"),
    ("NaquadahEnriched","富集硅岩"),
    ("NaquadahOxideMixture","氧化富集硅岩混合物"),
    ("Naquadria","超能硅岩"),
    ("NaquadriaOxideMixture","氧化超能硅岩混合物"),
    ("Neodymium","钕"),
    ("Neutronium","中子"),
    ("Nichromite","镍铬矿"),
    ("Niobium","铌"),
    ("Niter","硝石"),
    ("Oilsands","油砂"),
    ("Olenite","铝电气石"),
    ("Opal","蛋白石"),
    ("OrangeDescloizite","橙钒铅铜"),
    ("Orichalcum","山铜"),
    ("Oriharukon","奥利哈钢"),
    ("Palladium","钯"),
    ("PalladiumMetallicPowder","钯金属"),
    ("Pentlandite","镍黄铁矿"),
    ("Perlite","珍珠岩"),
    ("Phosphate","磷酸盐"),
    ("PigIron","生铁"),
    ("Plutonium","钚-239"),
    ("Plutonium241","钚-241"),
    ("Pollucite","铯榴石"),
    ("Polycrase","锗铀钇矿"),
    ("Powellite","钼钙矿"),
    ("Praseodymium","镨"),
    ("Promethium","钷"),
    ("Pumice","浮岩"),
    ("Pyrite","黄铁矿"),
    ("Pyrope","镁铝榴石"),
    ("Quantium","量子"),
    ("RareEarthl","稀土I"),
    ("RareEarthlII","稀土II"),
    ("RareEarthlII","稀土II"),
    ("RarestMetalResidue","稀有金属渣"),
    ("Realgar","雄黄"),
    ("RedDescloizite","红钒铅锌"),
    ("RedFuchsite","红铬云母"),
    ("Redstone","红石"),
    ("Roastedlron","焙烧铁"),
    ("RoastedNickel","焙烧镍"),
    ("RockSalt","岩盐"),
    ("Rubidium","铷"),
    ("Runite","虚恩"),
    ("Rutile","金红石"),
    ("Saltpeter","硝石"),
    ("Samarium","钐"),
    ("SamarskiteY","铌钇矿(Y)"),
    ("SamarskiteYb","铌钇矿(Yb)"),
    ("Scandium","钪"),
    ("Shadow","暗影金属"),
    ("ShadowIron","暗影铁"),
    ("Silicon","硅"),
    ("SiliconSolarGrade","太阳能级硅(多晶硅)"),
    ("Silver","银"),
    ("Soapstone","皂石"),
    ("Sodalite","方钠石"),
    ("Spessartine","锰铝榴石"),
    ("Spodumene","锂辉石"),
    ("Stibnite","辉锑矿"),
    ("Strontium","锶"),
    ("Sulfur","硫"),
    ("Tantalite","钽铁矿"),
    ("Tantalum","钽"),
    ("Tartarite","溶火之石"),
    ("Tellurium","碲"),
    ("Temagamite","碲汞钯"),
    ("TengamRaw","生磁"),
    ("Terbium","铽"),
    ("Terlinguaite","黄氯汞"),
    ("Tetrahedrite","黝铜矿"),
    ("Thorianite","方钍石"),
    ("Thorium","钍"),
    ("Thulium","铥"),
    ("Tin","锡"),
    ("Titanite","榍石"),
    ("Titanium","钛"),
    ("Topaz","黄玉"),
    ("TricalciumPhosphate","磷酸三钙"),
    ("Trinium","三元金属"),
    ("Tritanium","三钛"),
    ("Trona","天然碱"),
    ("Tungstate","钨酸锂"),
    ("Tungsten","钨"),
    ("Uraninite","晶质铀矿"),
    ("Uranium","铀-238"),
    ("Uranium235","铀-235"),
    ("Uvarovite","钙铬榴石"),
    ("Vanadio-Oxy-Dravite","钒镁电气石"),
    ("Vanadium","钒"),
    ("VanadiumMagnetite","钒磁铁矿"),
    ("Vinteum","温特姆"),
    ("Vulcanite","胶木"),
    ("Vyroxeres","幽冥剧毒结晶"),
    ("Wittichenite","硫铋铜"),
    ("Wollastonite","硅灰石"),
    ("Wulfenite","钼铅矿"),
    ("Xenotime","磷钇"),
    ("YellowLimonite","黄褐铁矿"),
    ("Ytterbium","镱"),
    ("Yttrialite","硅钍钇"),
    ("Yttrium","钇"),
    ("Yttrocerite","铈钇矿"),
    ("Zeolite","沸石"),
    ("Zimbabweite","钛铌铅钠石"),
    ("Zinc","锌"),
    ("Zircon","锆石"),
    ("Zirconolite","钛锆酸钙"),
    ("Zircophyllite","锆星叶石"),
    ("Zirkelite","钛锆钍")
]


# 处理拼接逻辑
def generate_combinations(prefixes, suffixes_special, suffixes_non_special):
    output = []

    # 按顺序处理每个前缀
    for prefix, prefix_desc in prefixes.items():
        # 添加标题
        output.append("")
        output.append(f"=== {prefix_desc} ===")
        output.append("")

        # 处理特殊后缀
        for suffix, suffix_desc, remark in suffixes_special:
            combined = prefix_desc.replace("~", suffix_desc)
            if remark:
                combined += f" {remark}"
            output.append(f"{prefix}{suffix} // {combined}")

        # 处理非特殊后缀
        for suffix, suffix_desc in suffixes_non_special:
            combined = prefix_desc.replace("~", suffix_desc)
            output.append(f"{prefix}{suffix} // {combined}")

    return "\n".join(output)

result = generate_combinations(prefixes, suffixes_special, suffixes_non_special)

# 保存为纯文本文件
output_file_path = "./processed_output.txt"
with open(output_file_path, "w", encoding="utf-8") as f:
    f.write(result)

output_file_path